databases:
  - name: iLink
    databaseName: iLink
    user: iLink

services:
  - type: web
    name: iLink
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: iLink
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
